### ISSUE TITLE
More secure ignore_update_merges option

### ISSUE THREAD

**Issue by ryanmcnamara** [palantir/policy-bot#120]
supposing require branch up to date is required and ignore_update_merges option is set to true, it is currently possible to use the merge conflict editor in the UI to sneak a change past policybot. A user with an approved pr with merge conflicts can use the merge conflict editor to make additional changes. Policybot will consider this pr to just be a merge and so will not invalidate the change

**Comment by ryanmcnamara** [comment]
A couple possible solutions

1. Restrict the option to only clean merges (hard because determining if a merge is a clean merge is nontrivial)
2. Allow restricting the set of users that may make merges that count as ignoreable updates

**Comment by bluekeyes** [comment]
This is a follow up to #12, where I decided to allow this behavior to avoid the expensive process of recursively comparing Git trees.

**Comment by ashrayjain** [comment]
@bluekeyes what do you think about the second suggestion above 
```
Allow restricting the set of users that may make merges that count as ignoreable updates
```

I would be happy to PR this if this seems like an acceptable path forward.

This is causing us significant pain since we use this in conjunction with https://github.com/palantir/bulldozer and its auto update functionality and we would really like to whitelist just the bulldozer user's merge commits if possible.

**Comment by bluekeyes** [comment]
I think ignoring users sounds reasonable, but I'm worried that the `ignore_update_merges` option is getting too complicated with this additional option.

Are the other restrictions on merge commits (generated by the API, is a merge, one of the parents is on the target branch) relevant in this case or would you be equally happy with ignoring any commits attributed to the `bulldozer` user? A general "ignore commits by user" option might be simpler to understand and useful in other cases as well.

I will also look into the problem of detecting "clean" merges again, but I'm starting to suspect it is impossible to distinguish an edit to a file due to a conflict from an edit to a file as part of the merged changes without simulating the full merge.

**Comment by ashrayjain** [comment]
Yea, i think the `ignore_commits_by_user` will be reasonable also.
