### ISSUE TITLE
[Question] Can policy-bot approve PRs (required reviews) ?

### ISSUE THREAD

**Issue by huydinhle** [palantir/policy-bot#162]
Based on the README.md, it said that Policy bot can
```Automatically approve pull requests that meet specific conditions```

Does this mean that policy-bot can approve PRs ( in terms of `required reviews`) , or policy-bot can only approve the PR within the `required status check`  it created

**Comment by bluekeyes** [comment]
Right now policy-bot can only set a commit status that can be made a required status check. The intent is that policy-bot _replaces_ the required review condition, instead of being an additional requirement.

That said, if you have a use case for combining the two, it might be interesting to have policy-bot post a review (that could be required) when the status goes green.

**Comment by wyardley** [comment]
Our intention was to use it to allow auto-merge (under certain conditions) for projects which have a GitHub requirement of having N approving code reviews.

**Comment by NargiT** [comment]
you should use https://github.com/palantir/bulldozer for automerging when status checks are fullfield. we use it works very well with policy-bot.

**Comment by wyardley** [comment]
I don’t think Bulldozer solves this problem when code-owner review is required.

**Comment by NargiT** [comment]
If you configure policy bot with correct [requires](https://github.com/palantir/policy-bot/blob/develop/config/policy-examples/team-approval.yml#L10) and bulldozer to wait for [policy status to be fulfilled](https://github.com/palantir/bulldozer/blame/develop/README.md#L142). I believe you could achieve your requirements. Or I am missing something ?

**Comment by tquach** [comment]
@NargiT In Github, you can set the branch protection to require an explicit review. Neither Bulldozer or Palantir will actually post an review approval so the PR will remain "stuck" until someone manually approves the PR.

![image](https://user-images.githubusercontent.com/1059032/78046777-94867980-7345-11ea-83c2-468fdb92c646.png)

**Comment by NargiT** [comment]
> Right now policy-bot can only set a commit status that can be made a required status check. The intent is that policy-bot _replaces_ the required review condition, instead of being an additional requirement.
> 
> That said, if you have a use case for combining the two, it might be interesting to have policy-bot post a review (that could be required) when the status goes green.

@tquach policy replaces it as @bluekeyes said.

**Comment by tquach** [comment]
@NargiT I believe the request here is exactly what he mentioned after
>  ...  it might be interesting to have policy-bot post a review (that could be required) when the status goes green.

**Comment by wyardley** [comment]
When `BULLDOZER_PUSH_RESTRICTION_USER_TOKEN` is used, will it be able to ignore required reviews if the user owning that token is an admin on the repo? I notice it was marked deprecated in
https://github.com/palantir/bulldozer/pull/182
since github allows bypassing restrictions for bot users now - however, this still doesn't allow overriding code review requirements.

We do have policy-bot, but it's occasionally flaky, and there are also some other annoyances with it for our use case, so it would be really nice if bulldozer can use that token to override branch protection.

**Comment by bluekeyes** [comment]
@wyardley Bulldozer is pretty specific about when it uses that token. It will actually check the target branch protection settings to see if push restrictions are enabled before using the token instead of the application credentials. But if the preconditions are met, then yes, if the token is for an admin, Bulldozer should be able to override the required review check.

While the feature is deprecated, we don't have immediate plans to remove the functionality.

>We do have policy-bot, but it's occasionally flaky, and there are also some other annoyances with it for our use case

If there aren't already issues tracking these flakes or annoyances, please consider creating one! They may be things that are easy for us to fix or improve.

**Comment by derekjobst** [comment]
@wyardley is the CODE_OWNERS branch protection the main sticking point here? Is there a reason your team prefers to use that rather than a policy-bot "requires users/teams" rule to enforce approval by a specific group of contributors?

**Comment by wyardley** [comment]
@derekjobst I've changed orgs, so not a concern for me right now.

I don't remember all the reasons for this request; CODEOWNERS can include some useful things, such as auto-flagging people for review by team; not sure if that's something policy-bot also does. From my standpoint (as well as from my previous org's standpoint), I don't think this is a big question / concern at this point.

**Comment by derekjobst** [comment]
Thank you for the update. Yes, agreed that there are some nice to have things with CODEOWNERS. As far as I know, the `request_review` setting in policy-bot will provide similar functionality for automatically requesting reviews.

Since this not longer is a big concern I will go ahead and close this issue out.
