### ISSUE TITLE
Question: Ignored 1 approval from disqualified users

### ISSUE THREAD

**Issue by xiaotianq** [palantir/policy-bot#174]
We just launched policy-bot in our organizations.
However, For one PR, it got  `Ignored 1 approval from disqualified users` from some engineer's approval, however some engineer under same organizations can approve the PR and let the policy-bot passed.

Can you please help with this issue?

**Comment by xiaotianq** [comment]
Tested on another repo under same organization, the engineer whose approval got ignored on the previous repo is able to give approval on this repo and policy-bot caught this as a valid approval

**Comment by bluekeyes** [comment]
A user can be disqualified for several reasons, which should be noted in the logs (at debug level):

- The log message `rejecting approval by banned user` indicates that the user is not allowed because they are either the PR author or a contributor (author or committer of a commit in the PR) and the policy does not allow author or committer approval.
- The log message `ignoring approval by non-whitelisted user` indicates that a user who attempted to approve is not actually in the set of allowed approvers

My guess is you are hitting the first case: the engineer who could not approve in the first repository was a contributor to the PR and the rule does have `allow_author: true` or `allow_contributors: true` under the `options` key.

**Comment by xiaotianq** [comment]
Checked the commit, actually the PR has multiple committer and one of them is the engineer who is willing to give approval. It make sense now. Thanks
