### ISSUE TITLE
Set up policy-bot but get errors on Pull Request

### ISSUE THREAD

**Issue by xiaotianq** [palantir/policy-bot#206]
On PR page it says xxx=policy-bot[bot] overwrote status to 'failure'

Inside policy-bot dockers,  logs are below

`{"level":"warn","rid":"bschea0tiqt81o37bog0","github_event_type":"status","github_delivery_id":"13685e68-cca0-11ea-932e-b9b9a822620d","github_installation_id":xx,"github_repository_owner":"xxx","github_repository_name":"yy","audit":"xx/yy","github_sha":"xxxxxxxxxxxxxxx","time":"2020-07-23T04:50:48.488133339Z","message":"Entity 'xxx-policy-bot[bot]' overwrote status check 'policy-bot: master' to state='failure' description=''xx-policy-bot[bot]' overwrote status to 'failure'' targetURL=''"}`

Anything should be setup ?
We use ALB to route traffic to policy-bot box, the ALB logs shows 200s.

**Comment by bluekeyes** [comment]
You can fix this by setting the [`options.app_name`](https://github.com/palantir/policy-bot/blob/develop/config/policy-bot.example.yml#L88) server configuration option to match the name of the app in GitHub, `xxx-policy-bot` in your case.

**Comment by xiaotianq** [comment]
@bluekeyes  thanks for replying the question. Will get it fixed

**Comment by diegolamanno** [comment]
@bluekeyes I am dealing with the same issue. I set up the app using directly the docker image. Why is `app_name` is not included as part of the other environment variables if it is required to get it working correctly? 

Thank you!

**Comment by bluekeyes** [comment]
@diegolamanno Sorry, this is just an oversight. We run the bot using a configuration file internally, so the environment variables have been added as people request them and we've never gone through to make sure they are consistent. I suspect it hasn't been a problem so far because the default configuration file works if you can call the app `policy-bot` (possible for GitHub Enterprise, but not for GitHub.com).

The real fix for this is #207, which will remove the need for this property, but PRs to add more environment variables in the meantime (see `ParseConfig` in `server/config.go`) are welcome.
