### ISSUE TITLE
Creating docker image from Dockerfile

### ISSUE THREAD

**Issue by M-Bohram** [palantir/policy-bot#232]
I have issue regarding creating the docker image from the dockerfile in the docker directory. My question is how to create a docker image that works from this dockerfile, using the command: docker build . -t "tag"

Thanks in advance :)

**Comment by bluekeyes** [comment]
If you only need a Docker image for a release or develop version of Policy Bot, we publish these to Docker Hub: https://hub.docker.com/r/palantirtechnologies/policy-bot/

If you'd like to build your own image, you need to use the [`godelw`](https://github.com/palantir/godel) tool in the repository, since the Dockerfile uses special templating features from this tool. Run:

    ./godelw docker build --verbose

That will download the dependencies for Godel, build the Docker image, and create a local tag. Note that before you run this, you'll need to:

1. Install Go
2. Install NodeJS and Yarn
3. Run `yarn install` to install the front end dependencies
4. Run `yarn run build:production` to generate the front end assets

If you'd like to use a different tag than what Godel creates, you can retag the image using `docker tag` after it is built.
