### ISSUE TITLE
Stop re-requesting reviews when all-users mode is used

### ISSUE THREAD

**Issue by buffer51** [palantir/policy-bot#263]
We've encountered the following issues on a GitHub repository today:
- We have a PR that modifies a single file.
- That file is configured to require approval from a GitHub team, and the requesting mode is set to `all-users`.
- policy-bot requests the review from all the users of that GitHub team, as expected.
- A member reviews the PR (in this case the PR is rejected asking for changes).
- policy-bot immediately re-requests a review from the member that reviewed.

This triggers more email notifications than are necessary, but more importantly the state the PR is left in looks like it needs to be reviewed (i.e. action pending on the reviewing team) when it actually isn't.

**Comment by bluekeyes** [comment]
This is actually not due the `all-users` mode but a consequence of how approval and disapproval are implemented. Reviewer requests only happen if the overall approval status is "pending" but we forgot to account for disapproval in that check, since it is implemented in a separate code path. We'll need to refactor where reviewer requests happen to account for this.

**Comment by buffer51** [comment]
The reason I mentioned `all-users` is that requesting groups does not create this issue. I have PRs where I disapproved and policy-bot didn't re-request the group I'm part of.
