### ISSUE TITLE
feat: update required status checks for repository

### ISSUE THREAD

**Issue by devinburnette** [palantir/policy-bot#369]
We noticed while setting up policy bot for the first time on a repository that the `policy-bot: main` status check context was not available to select in the github branch protection settings because it was not in the list of "status checks in the last week for this repository" search box. Apparently, github will only let you populate this check with statuses that have already posted to the repository. This creates an additional step of having to let policy bot run once against a pull request without the required check. However, I did notice that you can add a new status check context via github's API.

I noticed there's a webhook that fires when installing policy bot on a repo with the event type `installation_repositories` that policy bot appears to be automatically subscribed when ran as as a github app. What if policy bot could just upsert the required status check branch protection rule automatically upon installation on a repository?

A couple things came to mind when noodling about this feature. The first being some people might not want their PRs to be totally blocked by policy bot in the case they need to get a hot fix out immediately without approval. The second being that I believe a feature like this would require the github app to have additional repository level permissions to write the branch protection rule. I could see a policy bot server config option allowing folks to opt-in to allowing policy bot to do this on their behalf. That way it's kind of like two layers of "are you sure?" Once in the server config, and once by the act of setting the permission on the github app.

Although the feature would be useful for some, I understand the risks associated with giving the app basically administrator access on repos. Just wanted to discuss here and see if this had been thought about before and what the general consensus was for an idea like this.

**Comment by bluekeyes** [comment]
Thanks for suggesting this feature. I'm pretty hesitant to support this for a couple reasons, including the ones you mentioned:

* Installing the Policy Bot app on a repository doesn't actually enable functionality. The bot will effectively ignore everything about the repository until you also add policy file. We implemented it this way so that users could smoothly opt-in repositories without needing an organization admin (or some kind of automation) to enable the bot for each new repository.
* Because of this behavior, there's a good chance that enabling the check would immediately block PR merges, including the PR that adds the policy file (unless admin overrides are still allowed.) Users taking advantage of this feature would have to be careful to add the policy file and installing the app in the correct order.
* As you mentioned, it requires that the app have write access to repository administration. This is probably not that big of a deal, but we do try to minimize permissions where we can.
* I'd like to keep the bot focused on review and approval workflows and implementing this starts to take it into repository configuration territory. At least at Palantir, we've found that there is a lot of power in automating GitHub configuration (branch protections, settings, permissions, teams, etc.) via some dedicated tool and I'd prefer if other bots didn't fight with or duplicate that automation. While we use a custom tool that isn't open source, [probot/settings](https://github.com/probot/settings) or the [GitHub Terraform provider](https://registry.terraform.io/providers/integrations/github) are two existing tools that cover similar functionality. Conveniently, the APIs let you require check contexts that may not exist yet. If you set up a system like this to initially manage branch protection rules, I think you'll find it can have many other benefits for standardization and rolling out changes.

All that said, I agree that it's pretty annoying that the GitHub UI will only allow you to select status checks that have been delivered recently. Assuming GitHub won't change this, I don't see any harm in having Policy Bot post a `success` status on the `HEAD` commit of the default branch when it is installed on a repository. That way, if you want to require the status in the UI, it should be available, but if you don't care about using or enforcing the bot, the status is easy to ignore and you might not even notice it exists.

Would that at least partially help out with your workflow?

**Comment by devinburnette** [comment]
@bluekeyes all good points, and thanks for the tool recommendations, i'm sure they will be useful for us also..

I like the idea of just posting a success status so that it's at least available in the UI. How would that affect the order of operations problem you mentioned? Does the current behavior just give you a successful status on PRs if installed but no policy yet? I guess either way this is fine and at a minimum it could be like verification of installation. 

Anyway, happy to play around and see what it looks like if we think it would be valuable.

**Comment by bluekeyes** [comment]
My idea for the initial status check is that it is an unconditional success (so ignores the presence/absence of a policy file) and only happens from the installation event. Because it is applied to a commit already on the default branch, we don't really have to worry about a false approval that bypasses the (eventual) policy and the status it is unlikely to show up in a pull request. Even if it did, it would be successful and not block anything.
