### ISSUE TITLE
FR: Handle approvals embedded in GHE review comments

### ISSUE THREAD

**Issue by asvoboda** [palantir/policy-bot#51]
Sometimes a user will make a slightly weird, but otherwise correct review, and we'll see something like 

User1 reviewed with a comment:
```
 👍 
```

Policybot looks at the comment text and the result of the github approval, but not the _text_ of the github approval. I believe this is covered in the slightly different [reviews api](https://developer.github.com/v3/pulls/reviews/), so these types of "approvals" aren't counted.

**Comment by NargiT** [comment]
IMHO It's redundant to look to the comment of a github approval, by definition when it is approved, the PR is validated. Do you have a use case ?

**Comment by bluekeyes** [comment]
We see this occasionally with users who are less familiar with GitHub and accidentally leave a "comment" review (instead of an "approve" review) with ":+1:" as the text of the comment and are then confused about why their comment wasn't counted by policy-bot.

As you said, because supporting this is redundant and encourages "bad" habits with GitHub, we haven't implemented it yet, but it happens enough in our environment that it was worth tracking in an issue.

**Comment by jgiannuzzi** [comment]
This also happens quite a bit in our organization, where users will be in the "Files changed" tab of the PR and leave a review _comment_ (thus not an approval or a request for change). This seems natural to them as they assume it's essentially the same as a regular comment. It also makes sense to them to leave the comment right there instead of switching back to the "Conversation" tab after reviewing the changes.

I think that adding matching review _comments_ (again, not approvals or requests for changes) to the candidates would be a nice improvement. To be clear, I am talking about the `body` field of [`PullRequestReview`](https://docs.github.com/en/free-pro-team@latest/graphql/reference/objects#pullrequestreview) objects whose `state` field has the value `COMMENTED`. Review comments on specific code lines would thus not be considered.

If you agree, I am willing to submit a PR implementing this.

**Comment by bluekeyes** [comment]
@jgiannuzzi that sounds reasonable to me, if you'd like to submit a PR. For the implementation, I think you'll want to include these in the return from`pull.Context#Comments()`. Once there, everything else should work without changes. I can't think of a reason why we'd want to treat these differently from regular comments.

**Comment by jgiannuzzi** [comment]
Thanks for the tip, @bluekeyes! I have submitted a PR with your suggested implementation.
