### ISSUE TITLE
Unexpected Failure status check added in shared org

### ISSUE THREAD

**Issue by gpadavala** [palantir/policy-bot#533]
We have enabled the app in our shared organisation and suddenly we got complaints from couple of users from other team stating they had failure status on their commits

Failed Status Check looked like below
Policy Bot: develop — Error loading policy from <ORG_NAME>/.github

the policy file is not available in both the mentioned user's repo and the org's .github repo

It seems like it has posted a status check when it failed to read the policy from ".github" repo, but i would assume it would ignore (as it was unable to find the policy file)

Please let me know if this is expected or if this is a bug or if there is some known workaround for this

**Comment by bluekeyes** [comment]
This sounds like another instance of #506 / #405. If you have access to the bot's logs, my guess is that this is happening because GitHub returned errors while Policy Bot tried to load the policy from the organization level. Unfortunately, we don't have a fix for this right now.

If you are only using the bot on a small number of repositories, you may want to enable it on specific repositories instead of on the full organization, which should help prevent these errors for other teams.
