### ISSUE TITLE
has_successful_status may use incorrect check-run

### ISSUE THREAD

**Issue by stevoland** [palantir/policy-bot#821]
It seems that there are situations where the github api can return multiple "latest" check-runs (for a given sha & check-run name) and policy-bot uses the least recent.

eg: I pushed this workflow:

```
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ $PR_NUMBER == '1' ]; then
            echo "First PR, failing"
            exit 1
          else
            echo "Passing"
            exit 0
          fi
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
```

and opened PR 1. The job failed then I closed the PR.

Then I opened PR 2 and the job succeeds.

Looking at the query that I think policy-bot makes, there are 2 runs for `test` and I think policy-bot uses the last (least recent) one. Strangely both runs reference PR 2.

```
curl -L \
  -H "Accept: application/vnd.github.antiope-preview+json" \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/<org>/<repo>/commits/c4bb5fb/check-runs?filter=latest \
    | jq '.check_runs[] | {name,completed_at,conclusion,pull_requests}'

{
  "name": "test",
  "completed_at": "2024-08-14T07:23:49Z",
  "conclusion": "success",
  "pull_requests": [
    {
      "number": 2,
      ...
    }
  ]
}
{
  "name": "test",
  "completed_at": "2024-08-14T07:22:49Z",
  "conclusion": "failure",
  "pull_requests": [
    {
      "number": 2,
      ...
    }
  ]
}
```

Choosing the first (most recent) run would fix this case but I guess there can be other scenarios where the same commit has multiple "latest" check-runs

**Comment by stevoland** [comment]
Had a play and it seems github itself has the same limitation, only they choose the conclusion from the most recent run.

They make no distinction between check-runs from different PRs (eg to different base branches) with the same head ref.

**Comment by bluekeyes** [comment]
Good catch, this is definitely a bug in Policy Bot - it should only use the most recent conclusion for a given check, but we iterate over all of them and keep the last (oldest) one :

https://github.com/palantir/policy-bot/blob/9e5f2ff3d8fefcad351827ee70454b679cf95468/pull/github.go#L822-L824

We do the correct thing for traditional statuses, so this is only an issue for check runs.

> They make no distinction between check-runs from different PRs (eg to different base branches) with the same head ref.

Yeah, this is a confusing thing about GitHub's check/status implementation. Despite how much it looks like checks are attached to pull requests in the UI, in the data model and API, checks and statuses are attached only to commits. Since commits can appear in multiple branches and PRs, it can lead to situations like this.
