### ISSUE TITLE
switch to using github api v4

### ISSUE THREAD

**Issue by jmcampanini** [palantir/policy-bot#9]
we should look into switching to using the graphql version of the API for GHE. this would give us `pushed` timestamps, making `invalidate_on_push` a lot simpler.

a sample query for this would look like:

```
{
  repository(owner: "gradle", name: "gradle") {
    pullRequest(number: 5813) {
      comments(first: 100) {
        pageInfo {
          endCursor
          hasNextPage
        }
        nodes {
          body
          createdAt
        }
      }
      reviews(first: 100) {
        nodes {
          createdAt
          author {
            login
          }
          state
        }
      }
      commits(first: 100) {
        nodes {
          commit {
            pushedDate
            author {
              user {
                login
              }
            }
            committer {
              user {
                login
              }
            }
          }
        }
      }
    }
  }
}
```

As a note, we still need to use the v3 API for changed files, since these are not exposed via GraphQL at this time.

**Comment by bluekeyes** [comment]
Instead of paging the three elements individually, #37 converts the Timeline API calls to use GraphQL. I suppose we could also go back to the pre-`invalidate_on_push` implementation, where each method on `pull.Context` made it's own API call. But given that all evaluations need all three of these lists, getting everything from the timeline is convenient (even if it includes events we ignore).
